const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const ts = require('typescript');
const source = fs.readFileSync(require('node:path').join(__dirname, '../lib/access.ts'), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const context = { exports: {} };
vm.runInNewContext(compiled, context);
const { getAccess, isPublicPath, isAdminPath } = context.exports;
assert.equal(getAccess({}).approved, false);
assert.equal(getAccess({ approvalStatus: 'pending' }).approved, false);
assert.equal(getAccess({ approvalStatus: 'revoked' }).approved, false);
assert.equal(getAccess({ approvalStatus: 'approved' }).approved, true);
assert.equal(getAccess({ approvalStatus: 'approved' }).admin, false);
assert.equal(getAccess({ role: 'admin' }).admin, true);
assert.equal(getAccess({ role: 'admin' }).approved, true);
assert.equal(getAccess({ role: 'support' }).approved, true);
assert.equal(getAccess({ role: 'support' }).staff, true);
assert.equal(getAccess({ role: 'support' }).admin, false);
assert.equal(getAccess({ role: 'student', approvalStatus: 'approved' }).staff, false);
assert.equal(getAccess({ role: 'unknown' }).staff, false);
assert.equal(getAccess({ role: 'student', approved: true }).approved, false);
for (const path of ['/', '/sign-in', '/sign-up', '/sign-in/factor-one']) assert.equal(isPublicPath(path), true, path);
for (const path of ['/shadow', '/admin', '/api/access', '/sign-in-fake']) assert.equal(isPublicPath(path), false, path);
for (const path of ['/admin', '/admin/students', '/api/admin/students', '/AddReadAloud', '/sentence', '/essays-admin', '/api/scrape']) assert.equal(isAdminPath(path), true, path);
for (const path of ['/shadow', '/readaloud', '/essays', '/api/shadowing']) assert.equal(isAdminPath(path), false, path);
console.log('Access policy: all assertions passed.');